export default async function handler(request, response) {
  if (request.method !== 'POST') {
    return response.status(405).json({ error: 'Method not allowed' });
  }

  const { query, selectedText } = request.body;

  if (!query) {
    return response.status(400).json({ error: 'Query is required' });
  }

  try {
    const { GoogleGenerativeAI } = require("@google/generative-ai");

    // In a real scenario, we would use an embedding model to find relevant chunks.
    // Since we don't have the API key or vector DB set up in this environment,
    // and to keep it simple for this demonstration, we will assume the selectedText
    // is the primary context if provided, or we will (mock) searching the book.

    // For a robust RAG, we would:
    // 1. Generate embedding for `query`.
    // 2. Query a vector store (e.g., Pinecone, or a local JSON loaded here) for top-k chunks.
    // 3. Construct prompt with context.

    // Here, we'll try to load the embeddings file if it exists, otherwise fallback to a generic response
    // or use the selectedText.

    let context = "";

    if (selectedText) {
      context = `User selected text from the book: "${selectedText}"\n\n`;
    }

    // Load mock data or real data if we had the ingestion script run
    let bookContent = [];
    try {
        const fs = require('fs');
        const path = require('path');
        // This file would be generated by the ingestion script
        const dataPath = path.join(process.cwd(), 'api', 'data.json');
        if (fs.existsSync(dataPath)) {
            bookContent = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
        }
    } catch (e) {
        console.error("Could not load book content", e);
    }

    // Simple keyword search if we have content (Mock RAG)
    if (!selectedText && bookContent.length > 0) {
        const keywords = query.toLowerCase().split(' ');
        const relevantChunks = bookContent.filter(chunk =>
            keywords.some(kw => chunk.text.toLowerCase().includes(kw))
        ).slice(0, 3);

        if (relevantChunks.length > 0) {
            context += "Relevant context from the book:\n" + relevantChunks.map(c => c.text).join("\n---\n") + "\n\n";
        }
    }

    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
         // Mock response if no API key
         return response.status(200).json({
             answer: "I am ready to answer your questions using Gemini! (Please configure GEMINI_API_KEY in Vercel). " +
                     (context ? "I see you have some context or selected text." : "")
         });
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const prompt = `You are a helpful teaching assistant for a Physical AI & Humanoid Robotics course.
    Use the following context to answer the user's question. If the answer is not in the context, say you don't know, but try to be helpful based on general knowledge of the field if appropriate, but clarify it's not from the text.

    Context:
    ${context}

    User Question: ${query}
    `;

    const result = await model.generateContent(prompt);
    const responseText = result.response.text();

    return response.status(200).json({ answer: responseText });

  } catch (error) {
    console.error(error);
    return response.status(500).json({ error: 'Internal Server Error' });
  }
}
